language: python
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coveralls pytest-cov flake8
  - python setup.py install
script:
  - flake8
  - pytest --cov-report term-missing --cov=carsons tests/
after_success: coveralls
